[project]
name = "sqlitecloud-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
    "sqlalchemy-sqlitecloud>=0.1.2",
    "sqlmodel>=0.0.22",
]
